#! /bin/bash

function fn_help() {
    echo "Example:"
    echo -e "\t${0} file.txt"
    echo -e "\t${0} -y -a 1 ./*.jpg"
    echo -e "\t\t-y, override file!"
    echo -e "\t\t-a, --algorithm   1 (default), 256, 512"
    exit 1
}
_shasum_algorithm=1
_override=false
while getopts hya: opt; do
    case $opt in
        h) fn_help ;;
        y) _override=true ; echo "!!! Will override files, because -y:" ;;
        a)
            case $OPTARG in
                (1) _shasum_algorithm=$OPTARG ; break ;;
                (256) _shasum_algorithm=$OPTARG ; break ;;
                (512) _shasum_algorithm=$OPTARG ; break ;;
            esac
            echo "-a \"$OPTARG\" option is wrong. " ; fn_help
        ;;
        ?) echo "error：$OPTARG" ; fn_help
    esac
done
shift $((OPTIND-1))
if [ ! "$1" ]; then fn_help ; fi

IFS=$'\n' #修改分隔符为换行符
for _file in $* ; do
    if [ ! -f $_file ] ; then echo "error: \"$_file\" not is valid files." ; fn_help ; fi
    _sha1=`shasum -a $_shasum_algorithm $_file`
    _sha1=${_sha1%% *} #获取文件哈希值
    _out_filedir=`realpath $_file` #获取文件绝对路径
    _out_filedir=${_out_filedir%/*}
    _suffix=${_file##*.} #获取文件后缀
    _out_file=$_out_filedir/$_sha1.$_suffix #输出文件
    _find_file=`find $_out_filedir -maxdepth 1 -type f -iname "$_sha1.$_suffix"`
    if [[ $_find_file ]] && ! $_override ; then
        echo "File: $_find_file"
        echo -e "\tIt exists in the \"$_out_filedir/\" folder."
        echo -e "\tIf your needs override: \"-y\""
        exit 2
    fi
    mv -v $_file $_out_file
done
